[Config FreeSpace]

**.scenario = "RURAL_MACROCELL"   # α bajo ≈ 2
**.fading = false
**.shadowing = false
**.dynamic_los = false

#; SINR alto y estable

#; throughput máximo

#; sin pérdidas

[Config TwoRayApprox]

**.scenario = "RURAL_MACROCELL"
**.fading = false
**.shadowing = false

# Alturas influyen en reflexión suelo
**.bgChannelModel.nodeb_height = 25m
**.bgChannelModel.ue_height = 1.5m

#; comportamiento similar a free space pero con más caída a distancia

[Config Shadowing]

**.scenario = "URBAN_MACROCELL"
**.fading = false
**.shadowing = true
**.correlation_distance = 50
**.dynamic_los = false

#; variaciones lentas de SINR

#; throughput irregular

#; efecto “edificios”

[Config Rayleigh]

**.scenario = "URBAN_MACROCELL"
**.fading = true
**.fading_type = "JAKES"
**.shadowing = false
**.dynamic_los = false

#; muchas caídas de señal

#; pérdidas de paquetes

#; throughput más bajo

[Config Rice]

**.scenario = "URBAN_MACROCELL"
**.fading = true
**.fading_type = "JAKES"
**.shadowing = false
**.dynamic_los = true

#; picos de SINR

#; mejor throughput

#; comportamiento más realista

[Config RayleighShadowing]

**.scenario = "URBAN_MACROCELL"
**.fading = true
**.fading_type = "JAKES"
**.shadowing = true
**.dynamic_los = false

#; canal muy degradado

#; peor caso realista

[Config Realistic]

**.scenario = "URBAN_MACROCELL"
**.fading = true
**.fading_type = "JAKES"
**.shadowing = true
**.dynamic_los = true
**.correlation_distance = 50

#; Log-normal + Rayleigh + Rice

[Config Alpha_Low]
**.scenario = "RURAL_MACROCELL"

[Config Alpha_Medium]
**.scenario = "URBAN_MACROCELL"

[Config Alpha_High]
**.scenario = "URBAN_MICROCELL"

#; variando alfa
#; Rural  → mejor cobertura
#; Urban  → intermedio
#; Micro  → peor cobertura

[Config DistanceTest]

*.ue[0].mobility.typename = "LinearMobility"
*.ue[0].mobility.initialX = 800m
*.ue[0].mobility.initialY = 200m
*.ue[0].mobility.speed = 20mps
*.ue[0].mobility.initialMovementHeading = 90deg

#; distancia ↑ → SINR ↓ → throughput ↓

[Config NoObstacles]
**.shadowing = false

[Config WithObstacles]
**.shadowing = true

#; “sin edificios vs con edificios”

#; Métricas a recoger: 
#; throughput (server)

#; packet loss

#; SINR (UL)

#; delay

#; Configurar cada prueba:

#; Free Space   ->   fading OFF
#; Shadowing    ->   shadowing ON
#; Rayleigh     ->   fading + JAKES
#; Rice         ->   dynamic_los ON
#; alfa         ->   scenario

#; Más importantes: 

#; FreeSpace vs Realistic

#; Rayleigh vs Rice

#; Shadowing on/off

#; Movimiento (distancia)